### ISSUE TITLE
Remove unused dependencies

### ISSUE THREAD

**Issue by aniketnk** [pes-alcoding-club/posterior#7]
**Is your feature request related to a problem? Please describe.**
There are many ununsed dependencies from package.json. Add them only as necessary.
Used the depcheck library to find them.
```sh
$ depcheck
Unused dependencies
* errorhandler
* nodemailer
* nodemailer-express-handlebars
Unused devDependencies
* @types/errorhandler
* @types/node
* @types/shelljs
* eslint-config-prettier
* eslint-config-strongloop
* eslint-plugin-prettier
* shelljs
* ts-node
```

**Describe the solution you'd like**
Use depcheck and remove unnecessary packages.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by aniketnk** [comment]
Should apply to boilerplate once #1 is merged.

**Comment by aniketnk** [comment]
@temanisparsh What's the status on this?

**Comment by temanisparsh** [comment]
Will push changes in a while
